package Projeto1;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeremias
 */
public class Cadfunc extends javax.swing.JFrame {

    /**
     * Creates new form Cadfunc
     */
    public Cadfunc(Vector vetfunc) {
        initComponents();
        txtcadfuncnome.grabFocus();
        this.setLocationRelativeTo(null);
        this.vetfunc = vetfunc;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlcadfuncnome = new javax.swing.JLabel();
        txtcadfuncnome = new javax.swing.JTextField();
        jlcadfunccargo = new javax.swing.JLabel();
        txtcadfunccargo = new javax.swing.JTextField();
        jlcadfuncsal = new javax.swing.JLabel();
        txtcadfuncsal = new javax.swing.JTextField();
        bntcadastrar = new javax.swing.JButton();
        bntvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");

        jLabel1.setText("Cadastrar Funcionário");

        jlcadfuncnome.setText("Nome");

        txtcadfuncnome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcadfuncnomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcadfuncnomeFocusLost(evt);
            }
        });
        txtcadfuncnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcadfuncnomeKeyPressed(evt);
            }
        });

        jlcadfunccargo.setText("Cargo");

        txtcadfunccargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcadfunccargoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcadfunccargoFocusLost(evt);
            }
        });
        txtcadfunccargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcadfunccargoKeyPressed(evt);
            }
        });

        jlcadfuncsal.setText("Salário");

        txtcadfuncsal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcadfuncsalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcadfuncsalFocusLost(evt);
            }
        });
        txtcadfuncsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcadfuncsalKeyPressed(evt);
            }
        });

        bntcadastrar.setText("Cadastrar");
        bntcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntcadastrarActionPerformed(evt);
            }
        });
        bntcadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bntcadastrarKeyPressed(evt);
            }
        });

        bntvoltar.setText("Voltar");
        bntvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntvoltarActionPerformed(evt);
            }
        });
        bntvoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bntvoltarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bntvoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlcadfuncsal)
                                .addGap(18, 18, 18)
                                .addComponent(txtcadfuncsal, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlcadfunccargo)
                                .addGap(18, 18, 18)
                                .addComponent(txtcadfunccargo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(108, 108, 108)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(jlcadfuncnome)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtcadfuncnome, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bntcadastrar)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntvoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlcadfuncnome)
                    .addComponent(txtcadfuncnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlcadfunccargo)
                    .addComponent(txtcadfunccargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlcadfuncsal)
                    .addComponent(txtcadfuncsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bntcadastrar)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int autenticar(String nome, String cargo, double sal) {
        if (!nome.equals("") && !cargo.equals("") && !(sal == 0)) {
            return 1;
        } else {
            String msg = "Você deixou algum campo vazio ou inseriu algum valor inválido!";
            JOptionPane.showMessageDialog(null, msg, "siscad", JOptionPane.WARNING_MESSAGE);
            return 2;
        }
    }

    private void bntvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntvoltarActionPerformed

        this.hide();
        principal = new Principal();
        principal.setVetfunc(vetfunc);
        principal.setVisible(true);
    }//GEN-LAST:event_bntvoltarActionPerformed

    private void bntcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntcadastrarActionPerformed

        this.nome = txtcadfuncnome.getText();
        this.cargo = txtcadfunccargo.getText();
        try {
            this.sal = Double.parseDouble(txtcadfuncsal.getText());
        } catch (Exception e) {
            this.sal = 0;
        }

        switch (autenticar(this.nome, this.cargo, this.sal)) {
            case 1:
                funcionario = new Funcionario(this.nome, this.cargo, this.sal);
                vetfunc.addElement(funcionario);
                String msg = "Funcionario cadastrado com sucesso!";
                JOptionPane.showMessageDialog(null, msg, "siscad", JOptionPane.INFORMATION_MESSAGE);
                txtcadfuncnome.setText("");
                txtcadfunccargo.setText("");
                txtcadfuncsal.setText("");
                txtcadfuncnome.grabFocus();
                break;
            default:
                msg = "ERRO. Tente novamente!";
                break;

        }

    }//GEN-LAST:event_bntcadastrarActionPerformed

    private void txtcadfuncnomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcadfuncnomeFocusGained
        txtcadfuncnome.setBackground(Color.gray);
    }//GEN-LAST:event_txtcadfuncnomeFocusGained

    private void txtcadfuncnomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcadfuncnomeFocusLost
        txtcadfuncnome.setBackground(Color.white);
    }//GEN-LAST:event_txtcadfuncnomeFocusLost

    private void txtcadfunccargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcadfunccargoFocusGained
        txtcadfunccargo.setBackground(Color.gray);
    }//GEN-LAST:event_txtcadfunccargoFocusGained

    private void txtcadfunccargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcadfunccargoFocusLost
        txtcadfunccargo.setBackground(Color.white);
    }//GEN-LAST:event_txtcadfunccargoFocusLost

    private void txtcadfuncsalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcadfuncsalFocusGained
        txtcadfuncsal.setBackground(Color.gray);
    }//GEN-LAST:event_txtcadfuncsalFocusGained

    private void txtcadfuncsalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcadfuncsalFocusLost
        txtcadfuncsal.setBackground(Color.white);
    }//GEN-LAST:event_txtcadfuncsalFocusLost

    private void bntcadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bntcadastrarKeyPressed
        this.nome = txtcadfuncnome.getText();
        this.cargo = txtcadfunccargo.getText();
        try {
            this.sal = Double.parseDouble(txtcadfuncsal.getText());
        } catch (Exception e) {
            this.sal = 0;
        }

        switch (autenticar(this.nome, this.cargo, this.sal)) {
            case 1:
                funcionario = new Funcionario(this.nome, this.cargo, this.sal);
                vetfunc.addElement(funcionario);
                String msg = "Funcionario cadastrado com sucesso!";
                JOptionPane.showMessageDialog(null, msg, "siscad", JOptionPane.INFORMATION_MESSAGE);
                txtcadfuncnome.setText("");
                txtcadfunccargo.setText("");
                txtcadfuncsal.setText("");
                txtcadfuncnome.grabFocus();
                break;
            default:
                msg = "ERRO. Tente novamente!";
                break;
        }
    }//GEN-LAST:event_bntcadastrarKeyPressed

    private void bntvoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bntvoltarKeyPressed
        this.hide();
        principal = new Principal();
        principal.setVetfunc(vetfunc);
        principal.setVisible(true);
    }//GEN-LAST:event_bntvoltarKeyPressed

    private void txtcadfuncnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcadfuncnomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtcadfunccargo.grabFocus();
        }
    }//GEN-LAST:event_txtcadfuncnomeKeyPressed

    private void txtcadfunccargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcadfunccargoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtcadfuncsal.grabFocus();
        }
    }//GEN-LAST:event_txtcadfunccargoKeyPressed

    private void txtcadfuncsalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcadfuncsalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.nome = txtcadfuncnome.getText();
            this.cargo = txtcadfunccargo.getText();
            try {
                this.sal = Double.parseDouble(txtcadfuncsal.getText());
            } catch (Exception e) {
                this.sal = 0;
            }

            switch (autenticar(this.nome, this.cargo, this.sal)) {
                case 1:
                    funcionario = new Funcionario(this.nome, this.cargo, this.sal);
                    vetfunc.addElement(funcionario);
                    String msg = "Funcionario cadastrado com sucesso!";
                    JOptionPane.showMessageDialog(null, msg, "siscad", JOptionPane.INFORMATION_MESSAGE);
                    txtcadfuncnome.setText("");
                    txtcadfunccargo.setText("");
                    txtcadfuncsal.setText("");
                    txtcadfuncnome.grabFocus();
                    break;
                default:
                    msg = "ERRO. Tente novamente!";
                    break;
            }
        }
    }//GEN-LAST:event_txtcadfuncsalKeyPressed

    public Vector getVetfunc() {
        return vetfunc;
    }

    public void setVetfunc(Vector vetfunc) {
        this.vetfunc = vetfunc;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntcadastrar;
    private javax.swing.JButton bntvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlcadfunccargo;
    private javax.swing.JLabel jlcadfuncnome;
    private javax.swing.JLabel jlcadfuncsal;
    private javax.swing.JTextField txtcadfunccargo;
    private javax.swing.JTextField txtcadfuncnome;
    private javax.swing.JTextField txtcadfuncsal;
    // End of variables declaration//GEN-END:variables

    private String nome;
    private String cargo;
    private double sal;

    private Vector vetfunc;
    private Funcionario funcionario;
    private Principal principal;
}
