/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto1;

import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeremias
 */
public class PesquisarNome extends javax.swing.JFrame {

    /**
     * Creates new form PesquisarNome
     */
    public PesquisarNome(Vector vetfunc) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.vetfunc = vetfunc;
        txtnome.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlnome = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        bntpesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxtresultpesq = new javax.swing.JTextArea();
        bntvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa");

        jlnome.setText("Nome");

        txtnome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomeFocusLost(evt);
            }
        });

        bntpesquisar.setText("Pesquisar");
        bntpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntpesquisarActionPerformed(evt);
            }
        });
        bntpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bntpesquisarKeyPressed(evt);
            }
        });

        atxtresultpesq.setEditable(false);
        atxtresultpesq.setColumns(20);
        atxtresultpesq.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        atxtresultpesq.setRows(5);
        jScrollPane1.setViewportView(atxtresultpesq);

        bntvoltar.setText("Voltar");
        bntvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntvoltarActionPerformed(evt);
            }
        });
        bntvoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bntvoltarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlnome)
                        .addGap(11, 11, 11)
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntpesquisar))
                    .addComponent(bntvoltar))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(bntvoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnome)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomeFocusGained
        txtnome.setBackground(Color.gray);
    }//GEN-LAST:event_txtnomeFocusGained

    private void txtnomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomeFocusLost
        txtnome.setBackground(Color.white);
    }//GEN-LAST:event_txtnomeFocusLost

    private void bntpesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bntpesquisarKeyPressed
        funcionario = new Funcionario();
        nomePes = txtnome.getText().toUpperCase();
        if(nomePes.equals("")){
            atxtresultpesq.setText("Nenhum funcionário encontrado!");
        }else{
            String msg = "";
            int a = 0;
            for(int i=0; i<vetfunc.size(); i++){
                funcionario = (Funcionario) vetfunc.elementAt(i);
                nome = funcionario.getNome().toUpperCase();
                if(nome.contains(nomePes)){
                    msg += "Funcionário encontrado!\n";
                    msg += "Nome: "+funcionario.getNome()+"\n";
                    msg += "Cargo: "+funcionario.getCargo()+"\n";
                    msg += "Sal: R$"+funcionario.getSal()+"\n";
                    msg += "----------------------------------\n";
                    a++;
                }
            }
            if(a==0){
                msg = "Nenhum funcionário encontrado!";
            }
            atxtresultpesq.setText(msg);
            txtnome.setText("");
        }
    }//GEN-LAST:event_bntpesquisarKeyPressed

    private void bntvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntvoltarActionPerformed
        principal = new Principal();
        principal.setVetfunc(vetfunc);
        this.hide();
        principal.setVisible(true);
    }//GEN-LAST:event_bntvoltarActionPerformed

    private void bntvoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bntvoltarKeyPressed
        principal = new Principal();
        principal.setVetfunc(vetfunc);
        this.hide();
        principal.setVisible(true);
    }//GEN-LAST:event_bntvoltarKeyPressed

    private void bntpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntpesquisarActionPerformed
        funcionario = new Funcionario();
        nomePes = txtnome.getText().toUpperCase();
        if(nomePes.equals("")){
            atxtresultpesq.setText("Nenhum funcionário encontrado!");
        }else{
            String msg = "";
            int a = 0;
            for(int i=0; i<vetfunc.size(); i++){
                funcionario = (Funcionario) vetfunc.elementAt(i);
                nome = funcionario.getNome().toUpperCase();
                if(nome.contains(nomePes)){
                    msg += "Funcionário encontrado!\n";
                    msg += "Nome: "+funcionario.getNome()+"\n";
                    msg += "Cargo: "+funcionario.getCargo()+"\n";
                    msg += "Sal: R$"+funcionario.getSal()+"\n";
                    msg += "----------------------------------\n";
                    a++;
                }
            }
            if(a==0){
                msg = "Nenhum funcionário encontrado!";
            }
            atxtresultpesq.setText(msg);
            txtnome.setText("");
        }
    }//GEN-LAST:event_bntpesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxtresultpesq;
    private javax.swing.JButton bntpesquisar;
    private javax.swing.JButton bntvoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlnome;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables

    private Principal principal;
    
    
    private Vector vetfunc;
    private Funcionario funcionario;
    private String nome = "";
    private String nomePes = "";

    public Vector getVetfunc() {
        return vetfunc;
    }

    public void setVetfunc(Vector vetfunc) {
        this.vetfunc = vetfunc;
    }
}
